### PR TITLE
Fully developed application

### PR DESCRIPTION
**Pull request by El-Potato-Slayer**
The branch was used to develop a functional event management application with user authentication and authorization

The program:
- Allows users to sign up, sign in, and log out.
- Users who aren't signed in cannot create events.
- Users aren't able to edit or delete the events of other users.
- The events are cataloged into an 'upcoming' and 'past' section.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Sinan Sevgi & Chad Van Wyk** 
Good job with your first submission for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] In your tests, you should have only one "expect" for each "it".
- [x] Remove commented code in events_controller.rb
- [x] Remove commented code in event.rb
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by mcrd25 — APPROVED** [review]
# Changes Approved

Hi Team,

Thanks for making the changes requested by the previous reviewer. 
There is no need for further review. You may move on.

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

If you liked my review, consider upskilling me on LinkedIn. And please do connect. [My LinkedIn](https://www.linkedin.com/in/mayadouglas/)


*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

**Comment by El-Potato-Slayer** [comment]
Another review has been requested, however, even though the project has been approved, we aren't able to submit it on the microverse dashboard.

**Comment by Georjane** [comment]
> Another review has been requested, however, even though the project has been approved, we aren't able to submit it on the microverse dashboard.

Hi there,
Can you try submitting on the Microverse dashboard again? 
Feel free to reach out to me on Slack if you are having any more issues, **_Witah Georjane_**.

**Comment by El-Potato-Slayer** [comment]
> Hi there,
> Can you try submitting on the Microverse dashboard again?
> Feel free to reach out to me on Slack if you are having any more issues, **_Witah Georjane_**.

Thank you! We're able to submit now

**Pull request merged**
